// Generated by CoffeeScript 1.6.3
var Timetable;

Timetable = (function() {
  function Timetable() {
    this.periodIds = ["period1", "period2", "period3", "period4", "period5", "period7", "period8", "period9", "after-school"];
  }

  Timetable.prototype.setDay = function(dayInfo) {
    var i, subject, _i, _len, _results;
    _results = [];
    for (i = _i = 0, _len = dayInfo.length; _i < _len; i = ++_i) {
      subject = dayInfo[i];
      _results.push(this.showPeriod(this.periodIds[i], this.periodIds[i + 1], subject, dayInfo[i + 1]));
    }
    return _results;
  };

  Timetable.prototype.showPeriod = function(id, nextId, subject, nextSubject) {
    $("#" + id).text(subject);
    if (subject === nextSubject) {
      $("#" + id).attr("rowspan", "2");
      return $("#" + nextId).hide();
    }
  };

  return Timetable;

})();

$(document).ready(function() {
  var friday, monday, thursday, timetable, tuesday, wednesday, week;
  timetable = new Timetable();
  monday = ["English", "Biology", "Biology", "Maths", "Maths", "German", "Art & Design", "Art & Design", "Ice Skating"];
  tuesday = ["Biology", "History", "Maths"];
  wednesday = ["Biology", "History", "Maths"];
  thursday = ["Biology", "History", "Maths"];
  friday = ["Biology", "History", "Maths"];
  week = [monday, tuesday, wednesday, thursday, friday];
  return timetable.setDay(monday);
});
